{
 "title": "Custom Metrics Dashboard",
 "description": "Dashboard for custom metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Number of Widgets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "widgets_total", "legendFormat": "Widgets Total" }
   ]
  },
  {
   "title": "Avg time to create Widgets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "widgets_creation_time_seconds_sum / widgets_creation_time_seconds_count",
     "legendFormat": "Avg Time In Seconds"
    }
   ]
  },
  {
   "title": "Number of MacGuffins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "macguffins_total", "legendFormat": "MacGuffins Total" }
   ]
  },
  {
   "title": "Avg time to create MacGuffins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "macguffins_creation_time_seconds_sum / macguffins_creation_time_seconds_count",
     "legendFormat": "Avg Time In Seconds"
    }
   ]
  },
  {
   "title": "Number of Gizmos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "gizmos_seconds_count", "legendFormat": "Gizmos Total" }
   ]
  },
  {
   "title": "Avg time to create Gizmos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "gizmos_seconds_sum / gizmos_seconds_count",
     "legendFormat": "Avg Time In Seconds"
    }
   ]
  }
 ]
}